language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: breakout-2d
  skip_cleanup: true
  api_key:
    secure: DHUm2f5wy3Gb5jmaLOBBbCPWtcm4QfYSbBqLeywNVx4BMMQfmjjBYORDap0gWTwwbq8Es1f/Bu7DlxCl6rcbplIhcH9VIM7IcisXOb9q4nzXfInLvuEblMkzcaPOJHRhhKGpDc9X0iv7FcIPclvfBhTy0nmyFpITJDC2rC55Oz3rpaHdGz7EfTnfNKjRktHl54QJZTl2yfxSahuLSRZkzRwTpXPt35OXufW3beNWIK1FhA2YoBh/D5EHXPMRgFc9PslpUf0QAa6Vmg18DCvve7UcmYbBpuY03mjG1f2U/6ZSNpPxPVRayPSvafEnpvV2zIFK6+FssLbUxn+miKFEQ8Wto9UG/G0mTb8dA08hEZOYLTdNMtx3zBZFIDF36d+GEIyk0y+OYidDHbFcbrvF+Px9ystVW+zpfcv0JaKBldFrHn3XaVn5YeQYTdk46mbnuNl3BFks3Ky7jPJOSWK1G8ZCh2wya2OwFjm3i7jXEG8sB6dGOAsE3ezwYR7Voa85hdkZiEE8n6R6A3P+1CW5MJ5pvbFCKI0KfXHv8Kl0AoJPnLgYwDgdxyJHED4+B82+45Ol2N4t0Oze+Mx3OsE8E6TGnzxWSuReWP93vXC+S7m1za0oJsHtB+PiI1YTnI1YE2LJElegGvNorkG7Vr6EKEoYpUouaT7KA2dNxLPguQw=
