language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: breakout-2d
  skip_cleanup: true
  api_key:
    secure: IATs90WTGYj7T0YOJ10f/cW6BOIlZNAmEpK52vnWszRgFFpwVmCxbwQkMNobni62qAWqN9iNWpB7lXaHjyyWxIZc5MyJCSoHtLfz8SJnmbQ6ATHcq4YCisidl44H0afRdrsEvpd2HNHi8QlbjAbE5XSs9Qwn8Y5s7ircLVgM8REVLr2JzgPJAQcF1UxNHNrBk2629FSkFQZL0YhnFKQr7EDx5arqO+OHpExL/xUXzY3vuhcfd/nh8aUBXgTc6x0jJ0ENJKxVTNKw2iL3jqKig/UeH9/8tuY+RJ/CRws1tTtRy/MGps+cmdEK6KjcMTIXWz31Sjepitc21Eq8pJRkQMUA9EnVt9ViVdaSpm8q0IHr8pFuESMN9yOyWqC6XxVLInslDvnWMcjqCCdquaRXRLNcGIVf/YNHBo8fsjthPX51Dx31Vjj4yjU59bTK5WJcKyKrskApZNkKbcCBmDCrtEOVQnUqKeK4kkVAo5HPRavddIHyPoGho2DAsUG87cDPcqmoFUkW3UGYGXq3BhSb9YXHOdw4cwTkyGp0Vn++1wI/QUiQhskXLXq9KsDZo0iirppuEIw//9tAVBmKuUKLD2g5sSdqVQ/Hu0j0Bil8ht/rJFDaRYWyOeT5XpIhathX6eyIkx412Fy4nGd91TO0hIxGJcfp0R0+9su42jD3Io0=
